#!/bin/csh
#$ -M demo@gmail.com     # Email address for job notification
#$ -m a          # Send mail when job begins, ends and aborts
#$ -pe smp 4      # environment and legal core size
#$ -q long       # Specify queue (should always be long)
#$ -N ex2   # Specify job name
#$ -t 1:4        

module load R

Rscript ex2.R
